// @flow
export const LOGIN_ASYNC = 'LOGIN_ASYNC';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_TIMEOUT = 'LOGIN_TIMEOUT';

export const LOAD_SERIES_ASYNC = 'LOAD_SERIES';
export const LOAD_SERIES_SUCCESS = 'LOAD_SERIES_SUCCESS';
export const LOAD_SERIES_ERROR = 'LOAD_SERIES_ERROR';

export const ADD_SERIES = 'ADD_SERIES';

export const INCREMENT_PROGRESS = 'INCREMENT_PROGRESS';